/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/_admin/papers_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Papers Health */
        get: operations["papers_health_api__admin_papers_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List papers (fast path: JSONL cache, fallback: Chroma) */
        get: operations["list_papers_chroma_api_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_dev/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Dev Data */
        post: operations["seed_dev_data__dev_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated chunks for a paper */
        get: operations["api_get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single chunk by id */
        get: operations["api_get_chunk_api_papers__paper_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chunks for a paper (optionally filtered by q) */
        get: operations["get_filtered_chunks_api_papers__paper_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_admin/refresh_chunks_cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Chunks Cache
         * @description Admin-only convenience endpoint. Reloads store/chunks/all_chunks.jsonl into memory.
         *     Use only from localhost or protect with auth in production.
         */
        post: operations["refresh_chunks_cache_api__admin_refresh_chunks_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_admin/refresh_papers_cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Papers Cache
         * @description Reload store/chunks/all_papers.jsonl into memory.
         *     Use only from localhost or protect with auth in production.
         */
        post: operations["refresh_papers_cache_api__admin_refresh_papers_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Embedding search (RAG hits) */
        post: operations["api_search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or fetch summary */
        post: operations["api_create_summary_api_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary/{summary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a saved summary */
        get: operations["api_get_summary_api_summary__summary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Topics
         * @description Return a light sample of metadata to allow simple topic UIs (no UMAP here).
         */
        get: operations["api_topics_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CanonicalChunk */
        CanonicalChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Paper Id */
            paper_id: string;
            /** Text */
            text: string;
            /** Chunk Index */
            chunk_index: number;
            /** Char Len */
            char_len: number;
            /** Header Path */
            header_path?: string[] | null;
            /** Pages */
            pages?: [
                number | null,
                number | null
            ] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** ChunkResponse */
        ChunkResponse: {
            /** Chunk Id */
            chunk_id: string;
            /** Text */
            text: string;
            /** Chunk Index */
            chunk_index: number;
            /** Char Len */
            char_len: number;
            /** Header Path */
            header_path?: string[] | null;
            /** Pages */
            pages?: [
                number | null,
                number | null
            ] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaperChunksResponse */
        PaperChunksResponse: {
            /** Paper Id */
            paper_id: string;
            /** Total */
            total: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkResponse"][];
        };
        /** PaperMeta */
        PaperMeta: {
            /** Paper Id */
            paper_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[] | null;
            /** N Chunks */
            n_chunks: number;
            /** Preview */
            preview?: string | null;
            /** Pages */
            pages?: number | null;
            /** Source File */
            source_file?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Pipeline Version */
            pipeline_version?: string | null;
            /** Embed Model */
            embed_model?: string | null;
        };
        /** PapersList */
        PapersList: {
            /** Papers */
            papers: components["schemas"]["PaperMeta"][];
        };
        /** SearchHit */
        SearchHit: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Score */
            score?: number | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Paper Id */
            paper_id?: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Q */
            q: string;
            /**
             * K
             * @default 6
             */
            k: number | null;
            /** Paper Id */
            paper_id?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** K */
            k: number;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Q */
            q?: string | null;
            /** Paper Id */
            paper_id?: string | null;
            /**
             * K
             * @default 6
             */
            k: number | null;
        };
        /** SummaryResult */
        SummaryResult: {
            /** Summary Id */
            summary_id: string;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Answer */
            answer: string;
            /** Rag */
            rag: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    papers_health_api__admin_papers_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_papers_chroma_api_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapersList"];
                };
            };
        };
    };
    seed_dev_data__dev_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperChunksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_chunk_api_papers__paper_id__chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filtered_chunks_api_papers__paper_id__chunks_get: {
        parameters: {
            query?: {
                q?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperChunksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_chunks_cache_api__admin_refresh_chunks_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_papers_cache_api__admin_refresh_papers_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_create_summary_api_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_summary_api_summary__summary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                summary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_topics_api_topics_get: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
